defmodule PhoenixAssets.Generators.TSTest do
  @moduledoc false

  use ExUnit.Case, async: true

  doctest PhoenixAssets.Generators.TS

  alias PhoenixAssets.Generators.TS

  test "string_union/1 falls back to never for an empty list" do
    assert TS.string_union([]) == "never"
  end

  test "header/0 is a stable do-not-edit marker" do
    assert TS.header() =~ "Generated by phoenix_assets"
  end
end
