defmodule PhoenixAssets.Generators.TSTest do
  @moduledoc false

  use ExUnit.Case, async: true

  doctest PhoenixAssets.Generators.TS

  alias PhoenixAssets.Generators.TS

  test "string_union/1 falls back to never for an empty list" do
    assert TS.string_union([]) == "never"
  end

  test "header/0 is a stable do-not-edit marker" do
    assert TS.header() =~ "Generated by phoenix_assets"
  end

  test "camelize/1 returns an empty string for an empty input" do
    assert TS.camelize("") == ""
    assert TS.camelize(:"") == ""
  end

  test "type_name/1 pascalizes a plain (non-module) atom" do
    assert TS.type_name(:portfolio_row) == "PortfolioRow"
  end

  test "type names must be valid TypeScript identifiers" do
    assert_raise ArgumentError, fn -> TS.type_name("bad-name") end
    assert_raise ArgumentError, fn -> TS.type_name("class") end
  end

  test "url_template/1 escapes static template-literal syntax" do
    assert TS.url_template(~S|/api/`${value}/:id|) ==
             ~S|/api/\`\${value}/${encodeURIComponent(String(id))}|
  end

  test "primitive/1 maps the remaining primitive kinds" do
    assert TS.primitive(:boolean) == "boolean"
    assert TS.primitive(:map) == "Record<string, unknown>"
    assert TS.primitive(:anything_else) == "unknown"
  end
end
