defmodule PhoenixAssets.Generators.TS do
  @moduledoc """
  Shared helpers for rendering generated TypeScript.

  Every generator (routes, env, and -- in the stack package -- types, electric,
  pubsub, locales) emits TypeScript through these helpers so the output style is
  uniform: the same do-not-edit header, the same camelCase/PascalCase casing, and
  the same string-literal union rendering.

  ## Why

  Consistent casing and a single header string keep generated output stable and
  recognisably machine-written, and centralising them avoids each generator
  reinventing slightly different rules (which would surface as spurious diffs).
  """

  @header "// Generated by phoenix_assets. Do not edit by hand.\n"

  # ECMAScript reserved words plus strict-mode and contextual reservations:
  # none of these may appear as a parameter name in generated TypeScript.
  @reserved ~w(
    arguments await break case catch class const continue debugger default
    delete do else enum eval export extends false finally for function if
    implements import in instanceof interface let new null package private
    protected public return static super switch this throw true try typeof
    var void while with yield
  )

  @identifier ~r/^[A-Za-z_$][A-Za-z0-9_$]*$/

  @doc "The standard do-not-edit header prepended to every generated file."
  @spec header() :: String.t()
  def header, do: @header

  @doc ~S"""
  Renders the `import type { … } from "$phoenix/types"` line for a list of type
  names, or an empty string when there are none.

      iex> PhoenixAssets.Generators.TS.type_import([])
      ""
      iex> PhoenixAssets.Generators.TS.type_import(["ArticleRow"])
      ~s(import type { ArticleRow } from "$phoenix/types"\n)
  """
  @spec type_import([String.t()]) :: String.t()
  def type_import([]), do: ""

  def type_import(types),
    do: ~s|import type { #{Enum.join(types, ", ")} } from "$phoenix/types"\n|

  @doc ~S"""
  Converts a value to a lowerCamelCase identifier safe as a TS parameter name.

  Reserved words gain a trailing underscore and a leading digit gains a
  leading underscore, so a route param named `:new` or `:class` cannot emit
  invalid TypeScript.

      iex> PhoenixAssets.Generators.TS.arg_name("user_id")
      "userId"
      iex> PhoenixAssets.Generators.TS.arg_name("new")
      "new_"
  """
  @spec arg_name(atom() | String.t()) :: String.t()
  def arg_name(value) do
    name = camelize(value)

    cond do
      name in @reserved -> name <> "_"
      name =~ ~r/^[0-9]/ -> "_" <> name
      true -> name
    end
  end

  @doc ~S"""
  Converts a list of raw parameter names to unique lowerCamelCase argument
  names, in order.

  Two distinct route placeholders can camelize to the same identifier (`user_id`
  and `userId` both become `userId`); a collision gains a numeric suffix so the
  emitted TypeScript never declares duplicate parameters.

      iex> PhoenixAssets.Generators.TS.arg_names(["user_id", "userId"])
      ["userId", "userId2"]
  """
  @spec arg_names([atom() | String.t()]) :: [String.t()]
  def arg_names(params) do
    {names, _} =
      Enum.map_reduce(params, MapSet.new(), fn param, taken ->
        name = dedupe_arg(arg_name(param), taken)
        {name, MapSet.put(taken, name)}
      end)

    names
  end

  defp dedupe_arg(name, taken) do
    if MapSet.member?(taken, name) do
      Stream.iterate(2, &(&1 + 1))
      |> Stream.map(&"#{name}#{&1}")
      |> Enum.find(&(not MapSet.member?(taken, &1)))
    else
      name
    end
  end

  @doc ~S"""
  Renders a value as a TypeScript object key, quoting when it is not a plain
  identifier.

      iex> PhoenixAssets.Generators.TS.object_key(:user_id)
      "user_id"
      iex> PhoenixAssets.Generators.TS.object_key("kebab-case")
      ~s("kebab-case")
  """
  @spec object_key(atom() | String.t()) :: String.t()
  def object_key(value) do
    name = to_string(value)
    if Regex.match?(@identifier, name), do: name, else: JSON.encode!(name)
  end

  @doc ~S"""
  Converts a value to `lowerCamelCase`.

      iex> PhoenixAssets.Generators.TS.camelize(:public_portfolios)
      "publicPortfolios"
  """
  @spec camelize(atom() | String.t()) :: String.t()
  def camelize(value) do
    case value |> to_string() |> Macro.camelize() do
      "" -> ""
      <<first::utf8, rest::binary>> -> String.downcase(<<first::utf8>>) <> rest
    end
  end

  @doc ~S"""
  Converts a value to `UpperCamelCase` (PascalCase).

      iex> PhoenixAssets.Generators.TS.pascalize(:portfolio_row)
      "PortfolioRow"
  """
  @spec pascalize(atom() | String.t()) :: String.t()
  def pascalize(value), do: value |> to_string() |> Macro.camelize()

  @doc ~S"""
  Renders a TypeScript string-literal union from a list of values.

      iex> PhoenixAssets.Generators.TS.string_union([:public, :private])
      ~s("public" | "private")
  """
  @spec string_union([atom() | String.t()]) :: String.t()
  def string_union([]), do: "never"
  def string_union(values), do: Enum.map_join(values, " | ", &JSON.encode!(to_string(&1)))

  @doc ~S"""
  Returns the path-parameter names in a route path, covering both `:param`
  segments and `*glob` segments (without their sigil).

      iex> PhoenixAssets.Generators.TS.path_params("/users/:user_id/files/*path")
      ["user_id", "path"]
  """
  @spec path_params(String.t()) :: [String.t()]
  def path_params(path) do
    path
    |> String.split("/")
    |> Enum.flat_map(fn
      ":" <> param -> [param]
      "*" <> param -> [param]
      _ -> []
    end)
  end

  @doc ~S"""
  Renders a JS template-literal body for a route path, interpolating camelCased,
  URL-encoded parameters.

  `:param` segments encode as one URI component; `*glob` segments span multiple
  path segments, so each segment is encoded individually and the slashes are
  preserved.

      iex> PhoenixAssets.Generators.TS.url_template("/users/:user_id")
      "/users/${encodeURIComponent(String(userId))}"
  """
  @spec url_template(String.t()) :: String.t()
  def url_template(path) do
    names = path |> path_params() |> arg_names()

    {segments, _} =
      path
      |> String.split("/")
      |> Enum.map_reduce(names, fn
        ":" <> _, [name | rest] ->
          {"${encodeURIComponent(String(#{name}))}", rest}

        "*" <> _, [name | rest] ->
          {"${String(#{name}).split(\"/\").map(encodeURIComponent).join(\"/\")}", rest}

        segment, rest ->
          {segment, rest}
      end)

    Enum.join(segments, "/")
  end

  @doc ~S"""
  Derives a TypeScript type name from a string or a module-like atom.

      iex> PhoenixAssets.Generators.TS.type_name(PhoenixAssets.Generators.TS)
      "TS"
      iex> PhoenixAssets.Generators.TS.type_name("PortfolioRow")
      "PortfolioRow"
  """
  @spec type_name(String.t() | atom()) :: String.t()
  def type_name(type) when is_binary(type), do: type

  def type_name(type) when is_atom(type) do
    case Atom.to_string(type) do
      "Elixir." <> _ -> type |> Module.split() |> List.last()
      other -> pascalize(other)
    end
  end

  @doc ~S"""
  Maps a primitive Elixir type atom to a TypeScript type, for inline payload shapes.

      iex> PhoenixAssets.Generators.TS.primitive(:integer)
      "number"
  """
  @spec primitive(atom()) :: String.t()
  def primitive(type) when type in [:string, :binary, :id, :uuid, :date, :datetime], do: "string"
  def primitive(type) when type in [:integer, :float, :number, :decimal], do: "number"
  def primitive(:boolean), do: "boolean"
  def primitive(:map), do: "Record<string, unknown>"
  def primitive(_), do: "unknown"
end
