defmodule PhoenixAssets.Generators.TS do
  @moduledoc """
  Shared helpers for rendering generated TypeScript.

  Every generator (routes, env, and -- in the stack package -- types, electric,
  pubsub, locales) emits TypeScript through these helpers so the output style is
  uniform: the same do-not-edit header, the same camelCase/PascalCase casing, and
  the same string-literal union rendering.

  ## Why

  Consistent casing and a single header string keep generated output stable and
  recognisably machine-written, and centralising them avoids each generator
  reinventing slightly different rules (which would surface as spurious diffs).
  """

  @header "// Generated by phoenix_assets. Do not edit by hand.\n"

  @doc "The standard do-not-edit header prepended to every generated file."
  @spec header() :: String.t()
  def header, do: @header

  @doc ~S"""
  Converts a value to `lowerCamelCase`.

      iex> PhoenixAssets.Generators.TS.camelize(:public_portfolios)
      "publicPortfolios"
  """
  @spec camelize(atom() | String.t()) :: String.t()
  def camelize(value) do
    case value |> to_string() |> Macro.camelize() do
      "" -> ""
      <<first::utf8, rest::binary>> -> String.downcase(<<first::utf8>>) <> rest
    end
  end

  @doc ~S"""
  Converts a value to `UpperCamelCase` (PascalCase).

      iex> PhoenixAssets.Generators.TS.pascalize(:portfolio_row)
      "PortfolioRow"
  """
  @spec pascalize(atom() | String.t()) :: String.t()
  def pascalize(value), do: value |> to_string() |> Macro.camelize()

  @doc ~S"""
  Renders a TypeScript string-literal union from a list of values.

      iex> PhoenixAssets.Generators.TS.string_union([:public, :private])
      ~s("public" | "private")
  """
  @spec string_union([atom() | String.t()]) :: String.t()
  def string_union([]), do: "never"
  def string_union(values), do: Enum.map_join(values, " | ", &Jason.encode!(to_string(&1)))

  @doc ~S"""
  Returns the path-parameter names (without the leading colon) in a route path.

      iex> PhoenixAssets.Generators.TS.path_params("/users/:user_id/posts/:id")
      ["user_id", "id"]
  """
  @spec path_params(String.t()) :: [String.t()]
  def path_params(path) do
    path
    |> String.split("/")
    |> Enum.filter(&String.starts_with?(&1, ":"))
    |> Enum.map(&String.trim_leading(&1, ":"))
  end

  @doc ~S"""
  Renders a JS template-literal body for a route path, interpolating camelCased,
  URL-encoded parameters.

      iex> PhoenixAssets.Generators.TS.url_template("/users/:user_id")
      "/users/${encodeURIComponent(String(userId))}"
  """
  @spec url_template(String.t()) :: String.t()
  def url_template(path) do
    path
    |> String.split("/")
    |> Enum.map_join("/", fn
      ":" <> param -> "${encodeURIComponent(String(#{camelize(param)}))}"
      segment -> segment
    end)
  end

  @doc ~S"""
  Derives a TypeScript type name from a string or a module-like atom.

      iex> PhoenixAssets.Generators.TS.type_name(PhoenixAssets.Generators.TS)
      "TS"
      iex> PhoenixAssets.Generators.TS.type_name("PortfolioRow")
      "PortfolioRow"
  """
  @spec type_name(String.t() | atom()) :: String.t()
  def type_name(type) when is_binary(type), do: type

  def type_name(type) when is_atom(type) do
    case Atom.to_string(type) do
      "Elixir." <> _ -> type |> Module.split() |> List.last()
      other -> pascalize(other)
    end
  end

  @doc ~S"""
  Maps a primitive Elixir type atom to a TypeScript type, for inline payload shapes.

      iex> PhoenixAssets.Generators.TS.primitive(:integer)
      "number"
  """
  @spec primitive(atom()) :: String.t()
  def primitive(type) when type in [:string, :binary, :id, :uuid, :date, :datetime], do: "string"
  def primitive(type) when type in [:integer, :float, :number, :decimal], do: "number"
  def primitive(:boolean), do: "boolean"
  def primitive(:map), do: "Record<string, unknown>"
  def primitive(_), do: "unknown"
end
